### ISSUE TITLE
请迁移至 Python3 (Please migrate to python3)

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/dde-qt-dbus-factory#2]
`libdframeworkdbus/generate_code.py` 仍然使用 python2。鉴于 python2 明年将停止维护，请尽早将该脚本迁移至 python3。

**Comment by felixonmars** [comment]
我在大约两年前就已经迁移这个脚本为 2/3 同时兼容，在 Arch 上一直以来是用 Python3 运行的。个人认为 shebang 写 python 不带版本表达 2/3 同时兼容应该是可行的……

**Comment by hillwoodroc** [comment]
https://github.com/linuxdeepin/dde-qt-dbus-factory/pull/16

**Comment by zhangn1985** [comment]
debian 11也移除了/usr/bin/python，只有python2，python3，软件包方面也只有python2/python3，并没有python这个软件包。

**Comment by ClayStan** [comment]
fixed by https://github.com/linuxdeepin/dde-qt-dbus-factory/commit/68c186a8a712de84c9635c9af0b8ecdb027fe9c7

Thanks
